

# This file was *autogenerated* from the file osp_module.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)# Sage 示例（概念性）
L = LieSuperalgebra("osp", [_sage_const_3 ,_sage_const_6 ])
V = L.highest_weight_module([_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ])  # [a; b1,b2,b3]
print(V.dimension())  # 输出 48
print(V.weight_multiplicities())

